/**:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.068
    max_hamming: 0

    detector:
      threads: 1
      decimate: 2.0
      blur: 0.0
      refine: True
      sharpening: 0.25
      debug: False

    pose_estimation_method: "pnp"

    tag:
      ids: [1, 2, 3, 4, 5, 6, 66]
      frames: [tag01, tag02, tag03, tag04, tag05, tag06, tag66]
      sizes: [0.068, 0.068, 0.068, 0.068, 0.068, 0.068, 0.072]
